project:
  type: website
  output-dir: docs
  resources:
    - robots.txt

website:
  page-navigation: true
  title: "Elena Cossu"
  site-url: https://elenacossu.github.io

  page-footer:
    left: "&copy; Copyright 2024, Elena Cossu"
    right: "This page is built with [Quarto](https://quarto.org/)."

  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: publications.qmd
        text: Publications
        
      - href: cv.qmd
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

