---
title: "Selected Talks"
editor: visual
---

-   2025, How Critical Events Shape Political Agendas on Multiculturalism in France, International Political Science Association (IPSA) Conference

-   2025, The Social Bases of Democracy in Europe, European Political Science Association (EPSA) Conference

-   2025, Measuring Illiberalism Using Text Data and Machine Learning, Third Annual CIVICA Political Behaviour and Institutions Conference (PoBI)

-   2025, Measuring Illiberalism Using Text Data and Machine Learning, ECPR Joint Sessions: Text-as-Data Analysis in Political Science: Unlocking Political Insights with New Research Tools

-   2025, Measuring Illiberalism Using Text Data and Machine Learning, Helsinki Conference on Emotions, Populism, and Polarisation (HEPP5)

-   2024, Measuring Illiberalism Using Text Data and Machine Learning, MethodsNet Conference

-   2022, Assessing the economic performance of a government characterised by populist rhetoric in Hungary: A synthetic control approach, ECPR General Conference

-   2021, Macroeconomics and Politics in Hungary: How an Illiberal Government Characterised by Populist Rhetoric Deals With its Public Budget, The Doctoral Student Association of the University of Pécs Conference (PTE DOK)

-   2021, Macroeconomics, Policies, and CEE: a Machine Learning Approach to Social Investment and Social Protection Policies, inGRID Workshop

-   2020, A Review of Quasi-Experimental and Predictive Methodologies in Relation to Measuring Populism and its Outcomes, ASEEES 52nd Annual Convention

-   2020, FATIGUE Project Workshop, Science is Wonderful! European Commission Outreach Event, 2019

-   Economic populism, fiscal policies and budget deficits: the sustainability implications for Central and Eastern Europe, WINIR Symposium 2019

-   2019, Present and future populist policies in Europe: the Cases of Hungary and Bulgaria, RSA Winter Conference

-   2019, The New Populist Policies Prescriptions, UACES 49th Annual Conference
